"""GROMACS MD project generator (setup-only).

Generates a complete, downloadable GROMACS project (topology, mdp, run scripts,
report) for a protein–ligand complex. Does NOT execute production MD.

Force field defaults:
  Protein:  AMBER99SB-ILDN (built-in with GROMACS >= 2018)
  Ligand:   GAFF via ACPYPE (user runs acpype offline; template commands provided)
  Water:    TIP3P
  Ions:     0.15 M NaCl
"""
from __future__ import annotations
import io
import json
import os
import re
import shutil
import textwrap
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

MD_ROOT = Path(os.environ.get("MD_WORKDIR", "/tmp/phytonet_md"))
MD_ROOT.mkdir(parents=True, exist_ok=True)


@dataclass
class MDConfig:
    force_field: str = "amber99sb-ildn"
    water_model: str = "tip3p"
    box_type: str = "dodecahedron"    # cubic | dodecahedron | octahedron
    box_padding_nm: float = 1.0
    ion_concentration: float = 0.15
    positive_ion: str = "NA"
    negative_ion: str = "CL"
    temperature_K: float = 300.0
    pressure_bar: float = 1.0
    em_steps: int = 50000
    nvt_ps: int = 100
    npt_ps: int = 100
    production_ns: int = 100
    dt_fs: float = 2.0
    protein_name: str = "protein"
    ligand_name: str = "LIG"


MDP_MIN = """; Minimisation — steepest descent
integrator      = steep
emtol           = 1000.0
emstep          = 0.01
nsteps          = {em_steps}

nstxout         = 0
nstvout         = 0
nstenergy       = 500
nstlog          = 500

cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 20
rlist           = 1.0
coulombtype     = PME
rcoulomb        = 1.0
rvdw            = 1.0
pbc             = xyz
"""

MDP_NVT = """; NVT equilibration
title           = NVT equilibration
define          = -DPOSRES
integrator      = md
nsteps          = {nvt_steps}
dt              = {dt_ns}
nstxout         = 500
nstvout         = 500
nstenergy       = 500
nstlog          = 500
continuation    = no
constraint_algorithm = lincs
constraints     = h-bonds
lincs_iter      = 1
lincs_order     = 4

cutoff-scheme   = Verlet
nstlist         = 20
rlist           = 1.0
rcoulomb        = 1.0
rvdw            = 1.0
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.16

tcoupl          = V-rescale
tc-grps         = Protein_LIG Water_and_ions
tau_t           = 0.1 0.1
ref_t           = {temp} {temp}

pcoupl          = no
gen_vel         = yes
gen_temp        = {temp}
gen_seed        = -1
pbc             = xyz
"""

MDP_NPT = """; NPT equilibration
title           = NPT equilibration
define          = -DPOSRES
integrator      = md
nsteps          = {npt_steps}
dt              = {dt_ns}
nstxout         = 500
nstvout         = 500
nstenergy       = 500
nstlog          = 500
continuation    = yes
constraint_algorithm = lincs
constraints     = h-bonds

cutoff-scheme   = Verlet
nstlist         = 20
rlist           = 1.0
rcoulomb        = 1.0
rvdw            = 1.0
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.16

tcoupl          = V-rescale
tc-grps         = Protein_LIG Water_and_ions
tau_t           = 0.1 0.1
ref_t           = {temp} {temp}

pcoupl          = C-rescale
pcoupltype      = isotropic
tau_p           = 2.0
ref_p           = {pressure}
compressibility = 4.5e-5
refcoord_scaling = com

gen_vel         = no
pbc             = xyz
"""

MDP_PROD = """; Production MD
title           = Production
integrator      = md
nsteps          = {prod_steps}
dt              = {dt_ns}
nstxout         = 0
nstvout         = 0
nstxout-compressed = 5000
compressed-x-precision = 1000
nstenergy       = 5000
nstlog          = 5000
continuation    = yes
constraint_algorithm = lincs
constraints     = h-bonds

cutoff-scheme   = Verlet
nstlist         = 20
rlist           = 1.0
rcoulomb        = 1.0
rvdw            = 1.0
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.16

tcoupl          = V-rescale
tc-grps         = Protein_LIG Water_and_ions
tau_t           = 0.1 0.1
ref_t           = {temp} {temp}

pcoupl          = C-rescale
pcoupltype      = isotropic
tau_p           = 2.0
ref_p           = {pressure}
compressibility = 4.5e-5

pbc             = xyz
"""


BASH_SCRIPT = """#!/usr/bin/env bash
# Auto-generated by PhytoNet AI — GROMACS MD project driver
# Usage: bash run_md.sh
set -euo pipefail

# Prereqs: GROMACS (>=2021) + ACPYPE for ligand parameterisation.
# Place your receptor PDB as receptor.pdb (already stripped of water/hetatms).
# Place your ligand as ligand.mol2 (already parameterised via ACPYPE OR
# provide ligand.pdb and ACPYPE will run automatically).

if [ ! -f ligand.acpype/LIG_GMX.gro ]; then
  echo "[1/8] ACPYPE — ligand parameterisation with GAFF"
  acpype -i ligand.mol2 -b LIG -c gas
fi

echo "[2/8] pdb2gmx — protein topology with {force_field} + {water_model}"
gmx pdb2gmx -f receptor.pdb -o protein.gro -p topol.top -water {water_model} -ff {force_field} -ignh

echo "[3/8] Merge ligand into system"
python merge_topology.py

echo "[4/8] editconf — bounding box ({box_type}, {padding} nm padding)"
gmx editconf -f complex.gro -o complex_box.gro -bt {box_type} -d {padding} -c

echo "[5/8] solvate"
gmx solvate -cp complex_box.gro -cs spc216.gro -p topol.top -o complex_solv.gro

echo "[6/8] add ions (~{ion_conc} M NaCl)"
gmx grompp -f ions.mdp -c complex_solv.gro -p topol.top -o ions.tpr -maxwarn 2
echo "SOL" | gmx genion -s ions.tpr -o complex_ions.gro -p topol.top -pname {p_ion} -nname {n_ion} -conc {ion_conc} -neutral

echo "[7/8] energy minimisation ({em_steps} steps)"
gmx grompp -f minim.mdp -c complex_ions.gro -p topol.top -o em.tpr -maxwarn 2
gmx mdrun -deffnm em

echo "[8a/8] NVT equilibration ({nvt_ps} ps @ {temp} K)"
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm nvt

echo "[8b/8] NPT equilibration ({npt_ps} ps @ {pressure} bar)"
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm npt

echo "[8c/8] Production MD ({production_ns} ns)"
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm md
echo "Done. Analyse trajectory: gmx rms -s md.tpr -f md.xtc -o rmsd.xvg"
"""

POWERSHELL_SCRIPT = """<#
Auto-generated by PhytoNet AI — GROMACS MD project driver (Windows)
Usage: pwsh -File run_md.ps1
Requires: GROMACS + ACPYPE in PATH.
#>
$ErrorActionPreference = "Stop"

if (-not (Test-Path "ligand.acpype/LIG_GMX.gro")) {{
  Write-Host "[1/8] ACPYPE — ligand parameterisation"
  acpype -i ligand.mol2 -b LIG -c gas
}}
Write-Host "[2/8] pdb2gmx"
gmx pdb2gmx -f receptor.pdb -o protein.gro -p topol.top -water {water_model} -ff {force_field} -ignh
Write-Host "[3/8] merge topology"
python merge_topology.py
Write-Host "[4/8] editconf"
gmx editconf -f complex.gro -o complex_box.gro -bt {box_type} -d {padding} -c
Write-Host "[5/8] solvate"
gmx solvate -cp complex_box.gro -cs spc216.gro -p topol.top -o complex_solv.gro
Write-Host "[6/8] genion"
gmx grompp -f ions.mdp -c complex_solv.gro -p topol.top -o ions.tpr -maxwarn 2
"SOL" | gmx genion -s ions.tpr -o complex_ions.gro -p topol.top -pname {p_ion} -nname {n_ion} -conc {ion_conc} -neutral
Write-Host "[7/8] EM"
gmx grompp -f minim.mdp -c complex_ions.gro -p topol.top -o em.tpr -maxwarn 2
gmx mdrun -deffnm em
Write-Host "[8a] NVT"
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm nvt
Write-Host "[8b] NPT"
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm npt
Write-Host "[8c] Production"
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr -maxwarn 2 -n index.ndx
gmx mdrun -deffnm md
"""


MERGE_TOPOLOGY_PY = """#!/usr/bin/env python3
'''Very light protein + ligand topology merger.

Reads ligand.acpype/LIG_GMX.itp and appends it under the correct block in
`topol.top`, and combines protein.gro + LIG_GMX.gro into complex.gro.
'''
import re
from pathlib import Path

Path("topol.top").exists() or exit("topol.top missing")
Path("ligand.acpype/LIG_GMX.itp").exists() or exit("acpype output missing")

top = Path("topol.top").read_text()
itp = Path("ligand.acpype/LIG_GMX.itp").read_text()

# Insert ligand itp include right after forcefield include
lines = top.splitlines()
inc_idx = None
for i, l in enumerate(lines):
    if l.strip().startswith('#include') and 'forcefield.itp' in l:
        inc_idx = i + 1; break
if inc_idx is None:
    exit('forcefield include not found')
lines.insert(inc_idx, '#include "ligand.acpype/LIG_GMX.itp"')

# Append molecule to [molecules]
if not any('LIG' in l for l in lines):
    lines.append('LIG   1')

Path('topol.top').write_text('\\n'.join(lines))

# Concatenate gro files
prot = Path('protein.gro').read_text().splitlines()
lig  = Path('ligand.acpype/LIG_GMX.gro').read_text().splitlines()
title = prot[0]
n_prot = int(prot[1].strip()); n_lig = int(lig[1].strip())
merged = [title, str(n_prot + n_lig)]
merged.extend(prot[2:2 + n_prot])
merged.extend(lig[2:2 + n_lig])
merged.append(prot[-1])  # box vector
Path('complex.gro').write_text('\\n'.join(merged) + '\\n')
print(f'Merged {n_prot} protein atoms + {n_lig} ligand atoms -> complex.gro')
"""


INDEX_HELPER = """; Auto-generated helper — create group Protein_LIG & Water_and_ions
; Run:  gmx make_ndx -f em.gro -o index.ndx
; then paste:
;    1 | 13
;    name 20 Protein_LIG
;    14 | 15 | 16
;    name 21 Water_and_ions
;    q
"""


def _ps_to_steps(ps: float, dt_fs: float) -> int:
    return int(ps * 1000.0 / dt_fs)


def build_md_project(compound: Dict[str, Any],
                     target: Dict[str, Any],
                     receptor_pdb_content: Optional[str],
                     ligand_smiles_or_mol2: Optional[str],
                     cfg: MDConfig) -> Tuple[str, bytes]:
    """Create a zip package containing every file needed for MD.

    Args:
      compound: {name, smiles}
      target:   {gene_symbol, uniprot_id, pdb_id}
      receptor_pdb_content: optional PDB text (from docking receptor)
      ligand_smiles_or_mol2: SMILES string — ACPYPE will produce mol2 on the user's side.
      cfg: MDConfig instance controlling times/temperature/etc.
    Returns:
      (project_name, zip_bytes)
    """
    project = f"md_{compound['name']}_x_{target.get('gene_symbol','')}_{uuid.uuid4().hex[:6]}"
    project = re.sub(r"[^A-Za-z0-9_.-]", "_", project)[:80]
    buf = io.BytesIO()

    dt_ns = cfg.dt_fs / 1000.0
    ctx = {
        "force_field": cfg.force_field,
        "water_model": cfg.water_model,
        "box_type": cfg.box_type,
        "padding": cfg.box_padding_nm,
        "p_ion": cfg.positive_ion,
        "n_ion": cfg.negative_ion,
        "ion_conc": cfg.ion_concentration,
        "em_steps": cfg.em_steps,
        "nvt_ps": cfg.nvt_ps,
        "npt_ps": cfg.npt_ps,
        "production_ns": cfg.production_ns,
        "temp": cfg.temperature_K,
        "pressure": cfg.pressure_bar,
        "dt_ns": dt_ns,
        "nvt_steps": _ps_to_steps(cfg.nvt_ps, cfg.dt_fs),
        "npt_steps": _ps_to_steps(cfg.npt_ps, cfg.dt_fs),
        "prod_steps": int(cfg.production_ns * 1_000_000.0 / cfg.dt_fs),
    }

    report = _md_report(compound, target, cfg, ctx)

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        base = f"{project}/"
        zf.writestr(base + "README.md", _md_readme(compound, target, cfg))
        zf.writestr(base + "MD_PREPARATION_REPORT.md", report)
        zf.writestr(base + "minim.mdp", MDP_MIN.format(**ctx))
        zf.writestr(base + "ions.mdp", MDP_MIN.format(**ctx))
        zf.writestr(base + "nvt.mdp", MDP_NVT.format(**ctx))
        zf.writestr(base + "npt.mdp", MDP_NPT.format(**ctx))
        zf.writestr(base + "md.mdp", MDP_PROD.format(**ctx))
        zf.writestr(base + "run_md.sh", BASH_SCRIPT.format(**ctx))
        zf.writestr(base + "run_md.ps1", POWERSHELL_SCRIPT.format(**ctx))
        zf.writestr(base + "merge_topology.py", MERGE_TOPOLOGY_PY)
        zf.writestr(base + "make_index_helper.txt", INDEX_HELPER)
        zf.writestr(base + "commands.txt", _commands_text(ctx))
        if receptor_pdb_content:
            zf.writestr(base + "receptor.pdb", receptor_pdb_content)
        if ligand_smiles_or_mol2:
            zf.writestr(base + "ligand.smi", ligand_smiles_or_mol2)
        zf.writestr(base + "PROJECT_MANIFEST.json", json.dumps({
            "project": project, "compound": compound, "target": target,
            "config": {k: getattr(cfg, k) for k in cfg.__dataclass_fields__},
            "runtime_estimate": estimate_runtime(cfg, 30000),
        }, indent=2))
    return project, buf.getvalue()


def _md_readme(compound, target, cfg) -> str:
    return textwrap.dedent(f"""
    # {compound['name']} × {target.get('gene_symbol', target.get('uniprot_id',''))}
    Auto-generated GROMACS MD project — PhytoNet AI.

    ## Quick start
    ```bash
    # Prereqs on the run machine:
    #   • GROMACS ≥ 2021 in PATH
    #   • ACPYPE for ligand parameterisation
    #   • Python 3.8+
    bash run_md.sh
    ```

    ## Contents
    | File | Purpose |
    |------|---------|
    | receptor.pdb | Docking receptor (already stripped of HETATMs) |
    | ligand.smi   | Ligand SMILES (run acpype to obtain ligand.acpype/) |
    | minim.mdp, nvt.mdp, npt.mdp, md.mdp | GROMACS parameter files |
    | run_md.sh / run_md.ps1 | End-to-end driver scripts |
    | merge_topology.py | Merges protein + ACPYPE ligand topologies |
    | MD_PREPARATION_REPORT.md | Force field, box, times, hardware estimate |
    | commands.txt | Full command list — copy-paste ready |

    ## Force field / water / ions
    - Protein: **{cfg.force_field}**
    - Water:   **{cfg.water_model}**
    - Ions:    {cfg.positive_ion}/{cfg.negative_ion} @ {cfg.ion_concentration} M

    ## Simulation
    - Temperature: {cfg.temperature_K} K   ·   Pressure: {cfg.pressure_bar} bar
    - EM: {cfg.em_steps} steps   ·   NVT: {cfg.nvt_ps} ps   ·   NPT: {cfg.npt_ps} ps
    - Production: **{cfg.production_ns} ns** @ dt = {cfg.dt_fs} fs
    """).strip() + "\n"


def _md_report(compound, target, cfg, ctx) -> str:
    est = estimate_runtime(cfg, atoms=None)
    return textwrap.dedent(f"""
    # MD Preparation Report

    ## Target
    - Gene symbol: {target.get('gene_symbol','')}
    - UniProt: {target.get('uniprot_id','')}
    - PDB: {target.get('pdb_id','')}

    ## Ligand
    - Name: {compound['name']}
    - SMILES: {compound.get('smiles','')}

    ## Force field & water model
    - Force field: {cfg.force_field}  (AMBER family; well validated for globular proteins)
    - Water:       {cfg.water_model}
    - Ligand params: GAFF via ACPYPE (recommended) — CGenFF and OpenFF-2 are alternatives.

    ## Box
    - Shape: {cfg.box_type}
    - Padding: {cfg.box_padding_nm} nm around solute
    - Ions: {cfg.positive_ion}⁺ / {cfg.negative_ion}⁻ balanced to {cfg.ion_concentration} M

    ## Timing
    | Stage | Steps | Time |
    |-------|-------|------|
    | Energy min.  | {cfg.em_steps} | — |
    | NVT eq.      | {ctx['nvt_steps']} | {cfg.nvt_ps} ps |
    | NPT eq.      | {ctx['npt_steps']} | {cfg.npt_ps} ps |
    | Production   | {ctx['prod_steps']} | **{cfg.production_ns} ns** |
    | Time step    | — | {cfg.dt_fs} fs |

    ## Hardware & runtime estimate (assuming ~30 000 atoms)
    - CPU-only (32 cores): **~{est['cpu32']:.0f} h**
    - GPU (RTX 3090 / A100): **~{est['gpu']:.0f} h**
    - Recommended: ≥ 16 GB RAM, 50 GB free disk (trajectory), one CUDA-capable GPU.

    ## Reproducibility
    - Random seed: -1 (GROMACS default; log the actual seed after `mdrun`).
    - Constraints: h-bonds via LINCS.
    - Coulomb: PME, real-space cutoff 1.0 nm; LJ cutoff 1.0 nm.
    """).strip() + "\n"


def _commands_text(ctx) -> str:
    return textwrap.dedent(f"""
    # Full command list (copy-paste ready)
    acpype -i ligand.mol2 -b LIG -c gas
    gmx pdb2gmx -f receptor.pdb -o protein.gro -p topol.top -water {ctx['water_model']} -ff {ctx['force_field']} -ignh
    python merge_topology.py
    gmx editconf -f complex.gro -o complex_box.gro -bt {ctx['box_type']} -d {ctx['padding']} -c
    gmx solvate -cp complex_box.gro -cs spc216.gro -p topol.top -o complex_solv.gro
    gmx grompp -f ions.mdp -c complex_solv.gro -p topol.top -o ions.tpr -maxwarn 2
    echo "SOL" | gmx genion -s ions.tpr -o complex_ions.gro -p topol.top -pname {ctx['p_ion']} -nname {ctx['n_ion']} -conc {ctx['ion_conc']} -neutral
    gmx grompp -f minim.mdp -c complex_ions.gro -p topol.top -o em.tpr -maxwarn 2
    gmx mdrun -deffnm em
    gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -n index.ndx -maxwarn 2
    gmx mdrun -deffnm nvt
    gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -n index.ndx -maxwarn 2
    gmx mdrun -deffnm npt
    gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr -n index.ndx -maxwarn 2
    gmx mdrun -deffnm md
    """).strip() + "\n"


def estimate_runtime(cfg: MDConfig, atoms: Optional[int] = None) -> Dict[str, float]:
    """Rough wallclock estimate (hours) for the requested production time.

    Empirical rule-of-thumb from GROMACS benchmarks (as of 2024):
      CPU-only (32-core Xeon):  ~5-15 ns/day for a 30k-atom solvated complex.
      GPU (RTX 3090 / A100):    ~100-200 ns/day.
    """
    atoms = atoms or 30000
    scale = atoms / 30000.0
    ns_per_day_cpu = 10.0 / scale
    ns_per_day_gpu = 150.0 / scale
    return {
        "cpu32": (cfg.production_ns / ns_per_day_cpu) * 24.0,
        "gpu":   (cfg.production_ns / ns_per_day_gpu) * 24.0,
        "atoms_assumed": atoms,
    }
