// ResetPassword — /reset-password?token=... page that consumes a one-shot
// reset link generated by /api/auth/request-password-reset. Validates the
// two password fields client-side, calls /api/auth/reset-password, and
// redirects the user back to the marketing home on success.
import { useEffect, useMemo, useState } from "react";
import { useSearchParams, useNavigate, Link } from "react-router-dom";
import { Eye, EyeOff, Loader2, Lock, ShieldCheck, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

const BACKEND = process.env.REACT_APP_BACKEND_URL || "";

function scorePassword(pw) {
  if (!pw) return 0;
  let s = 0;
  if (pw.length >= 8)  s += 1;
  if (pw.length >= 12) s += 1;
  if (/[a-z]/.test(pw)) s += 1;
  if (/[A-Z]/.test(pw)) s += 1;
  if (/\d/.test(pw))    s += 1;
  if (/[^A-Za-z0-9]/.test(pw)) s += 1;
  return Math.min(4, Math.floor(s * 0.6));
}

export default function ResetPassword() {
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const token = params.get("token") || "";

  const [pw,  setPw]  = useState("");
  const [pw2, setPw2] = useState("");
  const [show, setShow] = useState(false);
  const [caps, setCaps] = useState(false);
  const [busy, setBusy] = useState(false);
  const [err, setErr]  = useState("");
  const [ok,  setOk]   = useState(false);

  useEffect(() => {
    if (!token) setErr("This reset link is missing its token. Please request a new link.");
  }, [token]);

  const strength = useMemo(() => scorePassword(pw), [pw]);
  const colors = ["#EF4444", "#F97316", "#F59E0B", "#22C55E", "#059669"];
  const labels = ["Very weak", "Weak", "Fair", "Strong", "Excellent"];

  const submit = async (e) => {
    e.preventDefault();
    setErr("");
    if (pw.length < 8) { setErr("Password must be at least 8 characters."); return; }
    if (pw !== pw2)     { setErr("Passwords do not match.");                return; }
    setBusy(true);
    try {
      const res = await fetch(`${BACKEND}/api/auth/reset-password`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ token, new_password: pw }),
      });
      const j = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(j?.detail || "Could not reset your password.");
      setOk(true);
      toast.success("Password reset — please sign in.");
      setTimeout(() => navigate("/"), 2200);
    } catch (ex) {
      setErr(ex.message || "Something went wrong.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="min-h-screen w-full bg-[#0F0E24] text-[#FAFAFF]">
      <div className="mx-auto flex min-h-screen max-w-xl items-center px-6 py-16">
        <div
          data-testid="reset-password-card"
          className="w-full overflow-hidden rounded-2xl border border-[#FAFAFF]/10 bg-[#12102E] shadow-[0_30px_80px_rgba(0,0,0,0.4)]"
        >
          <div className="border-b border-[#FAFAFF]/10 bg-gradient-to-br from-[#5139ED] via-[#395AED] to-[#8139ED] px-6 py-5">
            <div className="flex items-center gap-3">
              <span className="grid h-9 w-9 place-items-center rounded-xl bg-white/15 backdrop-blur">
                <ShieldCheck className="h-4 w-4" />
              </span>
              <div>
                <div className="font-headline text-[10.5px] font-bold uppercase tracking-[0.20em] text-white/80">
                  PhytoNet AI
                </div>
                <h1 className="font-headline text-[19px] font-bold">Reset your password</h1>
              </div>
            </div>
          </div>

          <div className="px-6 py-6">
            {ok ? (
              <div data-testid="reset-success" className="rounded-lg border border-emerald-400/40 bg-emerald-500/10 px-4 py-3 text-[13px] text-emerald-200">
                Password reset. Redirecting you to sign in…
              </div>
            ) : (
              <form onSubmit={submit} className="space-y-4">
                <p className="text-[13px] text-[#E7E7F3]/80">
                  Choose a new password — 8 characters minimum. Mix letters, numbers and a symbol
                  for a strong password.
                </p>

                <div>
                  <label className="text-[10px] font-bold uppercase tracking-widest text-[#E7E7F3]/60">
                    New password
                  </label>
                  <div className="relative mt-1">
                    <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#E7E7F3]/45" />
                    <input
                      data-testid="reset-pw"
                      type={show ? "text" : "password"}
                      required
                      minLength={8}
                      autoComplete="new-password"
                      value={pw}
                      onChange={(e) => setPw(e.target.value)}
                      onKeyDown={(e) => setCaps(e.getModifierState?.("CapsLock") || false)}
                      onKeyUp={(e) => setCaps(e.getModifierState?.("CapsLock") || false)}
                      className="w-full rounded-lg border border-[#FAFAFF]/10 bg-[#0F0E24] pl-9 pr-10 py-2.5 text-sm text-[#FAFAFF] placeholder:text-[#E7E7F3]/40 focus:border-[#5139ED] focus:outline-none"
                    />
                    <button
                      type="button"
                      data-testid="reset-pw-toggle"
                      onClick={() => setShow((s) => !s)}
                      aria-label={show ? "Hide password" : "Show password"}
                      className="absolute right-2 top-1/2 grid h-7 w-7 -translate-y-1/2 place-items-center rounded-md text-[#E7E7F3]/60 hover:bg-white/5 hover:text-[#c4b5fd]"
                    >
                      {show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                    </button>
                  </div>
                  {pw && (
                    <div className="mt-2">
                      <div className="flex gap-1">
                        {[0,1,2,3,4].map((i) => (
                          <div key={i} className="h-1 flex-1 rounded-full"
                               style={{ background: i <= strength ? colors[strength] : "rgba(250,250,255,0.10)" }} />
                        ))}
                      </div>
                      <div className="mt-1 text-[10.5px] font-semibold uppercase tracking-widest"
                           style={{ color: colors[strength] }}>
                        {labels[strength]}
                      </div>
                    </div>
                  )}
                  {caps && (
                    <div className="mt-1 inline-flex items-center gap-1 rounded-md bg-amber-500/15 px-2 py-1 text-[10.5px] font-semibold text-amber-300 ring-1 ring-amber-400/40">
                      <AlertTriangle className="h-3 w-3" /> Caps Lock is on
                    </div>
                  )}
                </div>

                <div>
                  <label className="text-[10px] font-bold uppercase tracking-widest text-[#E7E7F3]/60">
                    Confirm new password
                  </label>
                  <div className="relative mt-1">
                    <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#E7E7F3]/45" />
                    <input
                      data-testid="reset-pw2"
                      type={show ? "text" : "password"}
                      required
                      minLength={8}
                      autoComplete="new-password"
                      value={pw2}
                      onChange={(e) => setPw2(e.target.value)}
                      className="w-full rounded-lg border border-[#FAFAFF]/10 bg-[#0F0E24] pl-9 pr-3 py-2.5 text-sm text-[#FAFAFF] placeholder:text-[#E7E7F3]/40 focus:border-[#5139ED] focus:outline-none"
                    />
                  </div>
                </div>

                {err && (
                  <div data-testid="reset-error" className="rounded-lg border border-red-400/40 bg-red-500/10 px-3 py-2 text-[12px] text-red-300">
                    {err}
                  </div>
                )}

                <button
                  data-testid="reset-submit"
                  type="submit"
                  disabled={busy || !token}
                  className="inline-flex w-full items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[#5139ED] via-[#395AED] to-[#8139ED] px-5 py-3 text-sm font-bold uppercase tracking-widest text-white shadow-[0_10px_30px_-10px_rgba(81,57,237,0.6)] disabled:opacity-40"
                >
                  {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}
                  Reset password
                </button>

                <div className="text-center text-[11.5px] text-[#E7E7F3]/60">
                  Remembered it? <Link to="/" className="font-semibold text-[#c4b5fd] hover:underline">Back to sign in</Link>
                </div>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
